### PR TITLE
allowing optional paramaters to be not given

### PR DESCRIPTION
**Pull request by SamsTheGreatest**

### CODE REVIEW

**Review by britzl — CHANGES_REQUESTED** [review]
I just realised that we should change the order to avoid the _G.type function call if the value is not needed:

lua = lua + " assert(%s == nil or _G.type(%s) == '%s')\n" % (prop["name"], prop["name"], prop["type"])

Also, please run the code generator to create the generated socket.lua with your change. If you are not sure how, then I'll do it after this has been merged.

**Comment by SamsTheGreatest** [comment]
same seems need to be applied to function `match_join` so we are on the good track

**Comment by SamsTheGreatest** [comment]
Ran code gen and tested for some function like once above, all seems good. Shall I paste the new sockets code in to the git?

**Comment by britzl** [comment]
> Shall I paste the new sockets code in to the git?

Yes, please include it in the PR

**Pull request merged**
