### PR TITLE
allow skipping optional arguments

### PR DESCRIPTION
**Pull request by SamsTheGreatest**

### CODE REVIEW

**Review by britzl — CHANGES_REQUESTED** [review]
This is generated code. Changes should be made to the code generator template. More info about the code generator can be found here: https://github.com/heroiclabs/nakama-defold/tree/master/codegen

**Comment by SamsTheGreatest** [comment]
> This is generated code. Changes should be made to the code generator template. More info about the code generator can be found here: https://github.com/heroiclabs/nakama-defold/tree/master/codegen

Crazy stuff!

**Comment by britzl** [comment]
What we need is to change this:

https://github.com/heroiclabs/nakama-defold/blob/master/codegen/realtime.py#L203-L204

We want to check if a value is of the correct type or nil. Example:

```lua
assert(_G.type(some_string_var) == 'string' or some_string_var == nil)
```

So the relevant lines of the code generator should be changed to:

```python
	for prop in props:
		lua = lua + "	assert(_G.type(%s) == '%s' or %s == nil)\n" % (prop["name"], prop["type"], prop["name"])
```

**Comment by SamsTheGreatest** [comment]
@britzl I would guess this shall only happend for args[4:] as first 3 are essential?

**Comment by SamsTheGreatest** [comment]
Oh it's in python? Thank god...

**Comment by britzl** [comment]
> I would guess this shall only happen for args[4:] as the first 3 are essential? And only for this specific function right...

I would assume that there are other functions which also have optional arguments. We either do it for all functions and all arguments or none at all. How can we know which arguments that are optional if the API specification doesn't state it?

**Comment by SamsTheGreatest** [comment]
@britzl thats exactly what we discussed in the issue with missing docs... I guess if doing it for all of them would be a quick fix, but then if user doesnt give any parameters at all, lua will not throw any errors, only server will - could be a little more tricky to debug...

**Comment by SamsTheGreatest** [comment]
@britzl alright the argument actually makes a lot of sense. Just wish we had docs to refer to.. Lets go for the change.

**Comment by britzl** [comment]
Duplicate of https://github.com/heroiclabs/nakama-defold/pull/47

**Pull request closed without merging**
