### PR TITLE
Added Satori client support

### PR DESCRIPTION
**Pull request by britzl**

### CODE REVIEW

**Comment by lugehorsam** [comment]
@britzl Should the `satori` folder be added to `include_dirs` so that it can be fetched from Defold via git using the `dependencies` section?

**Comment by lugehorsam** [comment]
Can you add and use a session object just like in Nakama?

**Comment by britzl** [comment]
> @britzl Should the `satori` folder be added to `include_dirs` so that it can be fetched from Defold via git using the `dependencies` section?

Ah, yes, it should. I've added the folder.

**Comment by britzl** [comment]
> Can you add and use a session object just like in Nakama?

Yes, satori.authenticate() returns an api session. You can use satori.set_bearer_token() to set the session token for future requests. What that what you meant?

**Comment by lugehorsam** [comment]
@britzl could you add an example to the README?

**Comment by lugehorsam** [comment]
Could you also leave instructions for running the Satori SDK tests in the README?

**Comment by britzl** [comment]
> @britzl could you add an example to the README?

I've updated the readme with Satori info.

> Could you also leave instructions for running the Satori SDK tests in the README?

Added!

**Comment by britzl** [comment]
Docs PR: https://github.com/heroiclabs/docs/pull/680

**Review by DannyIsYog — APPROVED** [review]

**Comment by britzl** [comment]
@DannyIsYog thanks! Will you create a new release?

**Comment by DannyIsYog** [comment]
Hey @britzl, no worries :)
Feel free to make a new release, I belive you have permissions for that.

**Pull request merged**
