### PR TITLE
Fix encoding of empty lua table.

### PR DESCRIPTION
**Pull request by RonKip**
A fix for the following issue.
https://github.com/heroiclabs/nakama-defold/issues/17

### CODE REVIEW

**Comment by MrZak-dev** [comment]
Thanks to @RonKip ,
It works , i was able to create a match using 
```lua
local message = {
    match_create = {}
}
local result = nakama.socket.send(socket,message)
```

the only note is that there is a little issue in the code indentation , i guess @britzl who take care of checks .

**Comment by MrZak-dev** [comment]
@RonKip 
What if actually we meant to send an empty array for example , this will force all `[ ]` to be `{ }` without exceptions .
e.g : 
```lua
local match_data = {
    match_data_send = {
        match_id = match.match.match_id,
        op_code = 1337,
        data = {
            players = {} -- i want to receive it as an empty array
        }
    }
}
```
if i am not mistaken, in this case the players will be converted to Json object instead of an empty array of players

**Comment by novabyte** [comment]
@RonKip Thanks for the pull request. I think the best approach is to special case the encoded input to the empty Lua table for the specific function call rather than convert all usages.

**Comment by RonKip** [comment]
OK. That will be a better approach.

**Pull request closed without merging**
